# Generated by Django 3.2.5 on 2021-08-11 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 32, 23, 175876)),
        ),
        migrations.AddField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 32, 23, 175893)),
        ),
    ]
