# Generated by Django 3.2.5 on 2021-08-11 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210811_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 33, 11, 478506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 33, 11, 478527, tzinfo=utc)),
        ),
    ]
